# Generated by Django 4.2.2 on 2023-12-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdata'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdata'),
        ),
        migrations.AddField(
            model_name='links',
            name='direct_referred_link_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_referred_links', to='userapp.userdata'),
        ),
        migrations.AddField(
            model_name='links',
            name='indirect_referred_link_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_referred_links', to='userapp.userdata'),
        ),
        migrations.AddField(
            model_name='links',
            name='link_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_owner', to='userapp.userdata'),
        ),
        migrations.AddField(
            model_name='links',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
