# Generated by Django 4.2.2 on 2023-12-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_links_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='role',
        ),
    ]
