# Generated by Django 4.2.2 on 2023-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_links_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='role',
            field=models.CharField(choices=[('product', 'product'), ('influencer', 'influencer'), ('organiser', 'organiser')], default='product', max_length=50),
        ),
    ]
