# Generated by Django 4.2.2 on 2023-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_refferallink_product_created_by_product_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('influencer', 'influencer'), ('product', 'product'), ('organiser', 'organiser')], default='product', max_length=50),
        ),
    ]
