# Generated by Django 4.2.2 on 2023-12-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_alter_refferallink_link_holder_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='direct_referred_link_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_referred_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='indirect_referred_link_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirect_referred_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('influencer', 'influencer'), ('admin', 'admin'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
    ]
