# Generated by Django 4.2.2 on 2023-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refferallink',
            old_name='link_generated_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('influencer', 'influencer'), ('organiser', 'organiser'), ('admin', 'admin')], default='admin', max_length=50),
        ),
    ]
