# Generated by Django 4.2.2 on 2023-12-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_refferallink_link_holder_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('organiser', 'organiser'), ('admin', 'admin'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
