# Generated by Django 4.2.2 on 2023-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_refferallink_link_holder_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inclusive_GST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='product',
            name='influencer_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='product',
            name='organiser_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcription_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
