# Generated by Django 4.2.2 on 2023-12-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_refferallink_link_holder_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_fillment_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
