# Generated by Django 4.2.2 on 2023-12-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_refferallink_link_holder_current_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('organiser', 'organiser'), ('admin', 'admin'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('organiser', 'organiser'), ('admin', 'admin'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
