# Generated by Django 4.2.2 on 2023-12-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_rename_refferal_link_payment_user_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailsOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_done_at', models.DateField(auto_now_add=True, null=True)),
                ('payment_total_amount_paid', models.IntegerField(default=0)),
                ('payment_status_of_gateway', models.CharField(default='failed', max_length=25)),
                ('payment_order_id', models.CharField(default='0', max_length=100)),
                ('payment_signature', models.CharField(default='0', max_length=100)),
                ('pay_request_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_link', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.refferallink')),
            ],
        ),
        migrations.AddField(
            model_name='paymentrquest',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
