# Generated by Django 4.2.2 on 2023-12-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_paymentdetailsofproduct_paymentrquest_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetailsofproduct',
            old_name='pay_request_order_id',
            new_name='payment_id',
        ),
    ]
