# Generated by Django 4.2.2 on 2023-12-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_rename_pay_request_order_id_paymentdetailsofproduct_payment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetailsOfProduct',
            new_name='UserPaymentDetailsOfProduct',
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
