# Generated by Django 4.2.2 on 2023-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_rename_paymentdetailsofproduct_userpaymentdetailsofproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommisions',
            name='credited_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('organiser', 'organiser'), ('admin', 'admin'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('organiser', 'organiser'), ('admin', 'admin'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
