# Generated by Django 4.2.2 on 2023-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_usercommisions_credited_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommisions',
            name='credited_on',
        ),
        migrations.AddField(
            model_name='usercommisions',
            name='commission_credited_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('admin', 'admin'), ('influencer', 'influencer'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('admin', 'admin'), ('influencer', 'influencer'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
    ]
