# Generated by Django 4.2.2 on 2023-12-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_refferallink_link_holder_current_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCommisions',
            new_name='UserCommissions',
        ),
    ]
