# Generated by Django 4.2.2 on 2023-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_rename_usercommisions_usercommissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('influencer', 'influencer'), ('admin', 'admin'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('influencer', 'influencer'), ('admin', 'admin'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
    ]
