# Generated by Django 4.2.2 on 2023-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_alter_refferallink_link_holder_current_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('admin', 'admin'), ('organiser', 'organiser'), ('influencer', 'influencer')], default='admin', max_length=50),
        ),
    ]
