# Generated by Django 4.2.2 on 2023-12-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0054_alter_refferallink_link_holder_current_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_current_role',
            field=models.CharField(choices=[('admin', 'admin'), ('influencer', 'influencer'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='refferallink',
            name='link_holder_role_at_link_generation',
            field=models.CharField(choices=[('admin', 'admin'), ('influencer', 'influencer'), ('organiser', 'organiser')], default='admin', max_length=50),
        ),
        migrations.CreateModel(
            name='NetmagicsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
