# Generated by Django 4.2.2 on 2023-12-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_refferallink_link_holder_role'),
        ('userapp', '0005_userrequestingforupgradingtoorganiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestingforupgradingtoorganiser',
            name='user_refferal_link',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='product.refferallink'),
        ),
    ]
