# Generated by Django 4.2.2 on 2023-12-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userrequestingforupgradingtoorganiser_user_refferal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestingforupgradingtoorganiser',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='userrequestingforupgradingtoorganiser',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
