# Generated by Django 4.1.4 on 2023-12-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userrequestingforupgradingtoorganiser_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('local_body', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Region Data',
            },
        ),
        migrations.CreateModel(
            name='SupportingExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsx_file', models.FileField(upload_to='xlsx_files/')),
            ],
        ),
    ]
