# Generated by Django 4.1.4 on 2023-12-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_regiondata_supportingexceldata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionData',
            new_name='RegionDataVillage',
        ),
    ]
