# Generated by Django 4.2.2 on 2023-12-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_userrequestingforupgradingtoorganiser_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequestingforupgradingtoorganiser',
            old_name='approved_by',
            new_name='approved_or_reject_by',
        ),
    ]
