# Generated by Django 4.2.2 on 2023-12-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_rename_approved_by_userrequestingforupgradingtoorganiser_approved_or_reject_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_refferal_link',
        ),
    ]
