# Generated by Django 4.2.2 on 2023-12-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_userdetails_user_refferal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='region_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.regiondatavillage'),
        ),
    ]
