# Generated by Django 4.2.2 on 2023-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_userdetails_region_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='region_data',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='local_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sub_district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='village',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
