# Generated by Django 4.2.2 on 2023-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_userdetails_region_data_userdetails_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=500, null=True)),
                ('account_number', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=500, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=500)),
                ('check_or_passbook_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('pancard_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
