# Generated by Django 4.2.2 on 2023-12-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_refferallink_link_holder_current_role_and_more'),
        ('userapp', '0015_userbankaccountdetails_userdetails_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.refferallink'),
        ),
    ]
