# Generated by Django 4.2.2 on 2023-12-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_userbankaccountdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountdetails',
            name='branch_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
