# Generated by Django 4.2.2 on 2023-12-30 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_userbankaccountdetails_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccountdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
