# Generated by Django 4.2.2 on 2023-12-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_userbankaccountdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountdetails',
            name='current_primary_account',
            field=models.BooleanField(default=False),
        ),
    ]
